//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod collection;
pub mod config;
pub mod download_run;
pub mod favorite;
pub mod page;
pub mod submission;
pub mod upper_auto_manage_action;
pub mod upper_auto_manage_policy;
pub mod upper_auto_manage_run;
pub mod video;
pub mod watch_later;
