//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "upper_auto_manage_action")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub run_id: i32,
    pub submission_id: i32,
    pub upper_name: String,
    pub action: ActionType,
    pub reason: Option<String>,
    pub created_at: DateTime,
}

/// 巡检任务对单个 UP 主执行的操作类型
#[derive(Debug, Clone, Copy, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::N(32))")]
pub enum ActionType {
    /// 因长期不更新被自动禁用
    #[sea_orm(string_value = "auto_disabled")]
    AutoDisabled,
    /// 检测到恢复更新被自动重新启用
    #[sea_orm(string_value = "auto_enabled")]
    AutoEnabled,
    /// 检测到 UP 不可用被标记为黑名单
    #[sea_orm(string_value = "marked_banned")]
    MarkedBanned,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::upper_auto_manage_run::Entity",
        from = "Column::RunId",
        to = "super::upper_auto_manage_run::Column::Id"
    )]
    Run,
    #[sea_orm(
        belongs_to = "super::submission::Entity",
        from = "Column::SubmissionId",
        to = "super::submission::Column::Id"
    )]
    Submission,
}
impl Related<super::upper_auto_manage_run::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Run.def()
    }
}
impl Related<super::submission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Submission.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
