//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "upper_auto_manage_run")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub started_at: DateTime,
    pub finished_at: Option<DateTime>,
    pub status: RunStatus,
    pub checked_count: i32,
    pub disabled_count: i32,
    pub enabled_count: i32,
    pub banned_count: i32,
    pub banned_observation_count: i32,
    pub active_count: i32,
    pub indeterminate_count: i32,
    pub still_inactive_count: i32,
    pub error_message: Option<String>,
    pub summary: Option<String>,
}

/// 单次巡检任务的执行状态
#[derive(Debug, Clone, Copy, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::N(16))")]
pub enum RunStatus {
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "succeeded")]
    Succeeded,
    #[sea_orm(string_value = "failed")]
    Failed,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::upper_auto_manage_action::Entity")]
    Action,
}
impl Related<super::upper_auto_manage_action::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Action.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
