//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "upper_auto_manage_policy")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub submission_id: i32,
    pub policy: UpperManagePolicy,
    pub source: UpperManageSource,
    pub reason: Option<String>,
    pub updated_at: DateTime,
}

/// UP 主自动管理策略
#[derive(Debug, Clone, Copy, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::N(16))")]
pub enum UpperManagePolicy {
    /// 正常参与自动启停
    #[sea_orm(string_value = "normal")]
    Normal,
    /// 永不自动禁用
    #[sea_orm(string_value = "whitelist")]
    Whitelist,
    /// 禁用后永不自动重新启用
    #[sea_orm(string_value = "blacklist")]
    Blacklist,
}

/// 标记当前 submission 的 enabled 状态由谁设定
/// 仅在系统自动禁用时写入 Auto；用户手动切换 enabled 不写入 policy 行，自然不会被自动恢复
#[derive(Debug, Clone, Copy, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::N(16))")]
pub enum UpperManageSource {
    #[sea_orm(string_value = "manual")]
    Manual,
    #[sea_orm(string_value = "auto")]
    Auto,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::submission::Entity",
        from = "Column::SubmissionId",
        to = "super::submission::Column::Id"
    )]
    Submission,
}
impl Related<super::submission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Submission.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
